# Question 1
strsplit(names(communities), "wgtp")[123]
#######################################################

# Question 2
gdp <- read.csv("gdp.csv", skip=5, header=FALSE, nrows=190)
colnames(gdp) <- c("CountryCode", "Rank", "NO1", "Economy", "USD_M", "NO2", "NO3", "NO4",    "NO5", "NO6")
gdp2 <- subset(gdp, select=c("CountryCode", "Rank", "Economy", "USD_M"))

gdp2$USD_M <- as.numeric(gsub(",", "", gdp2$USD_M))
mean(gdp2$USD_M)

#Question 3
countryNames <- as.character(gdp2$Economy)
grep("^United", countryNames)

#Question 4
edu <- read.csv("edu.csv")
## > dim(gdp[gdp2$CountryCode %in% edu$CountryCode,]) -> 189 10
m <- merge(gdp2, edu, by="CountryCode", all.x=FALSE)
length(grep("June", m$Special.Notes))

""" 16, number of occurances, wasn't the correct answer [Options 16,31,13,15]: Manually Counting: 
 [1] Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [2] Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [3] Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[4] Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[5] Fiscal year end: June 30; reporting period for national accounts data: CY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[6] Fiscal year end: June 30; reporting period for national accounts data: CY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
xxx [7] Kosovo became a World Bank member on June 29, 2009. Since 1999, Kosovo has been a territory under international 
                                    administration pursuant to UN Security Council Resolution 1244 (1999).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
[8] Fiscal year end: June 30; reporting period for national accounts data: CY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
xxx [9] Montenegro declared independence from Serbia and Montenegro on June 3, 2006. Where available, data for each country 
            are shown separately. However, for Serbia, some indicators continue to include data for Montenegro through 2005.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
[10] Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[11] Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[12] Fiscal year end: June 30; reporting period for national accounts data: CY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
XXX [13] Montenegro declared independence from Serbia and Montenegro on June 3, 2006. Where available, data for each country 
            are shown separately. However, for Serbia, some indicators, such as those series for which data appear only 
            for Serbia and not Montenegro--e.g., aid, environment, external debt, balance of payments, various social 
            indicators excluding population--continue to include data for Montenegro through 2005. Moreover, data from 1999 
            onward for Serbia for most indicators exclude data for Kosovo, 1999 being the year when Kosovo became a territory 
            under international administration pursuant to UN Security Council Resolution 1244 (1999); any exceptions are noted. 
            Kosovo became a World Bank member on June 29, 2009; available data are shown separately for Kosovo. The Statistical 
            Bureau of Serbia has revised current and constant GDP for 1997-2006.
[14] Fiscal year end: June 30; reporting period for national accounts data: CY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[15] Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[16] Fiscal year end: June 30; reporting period for national accounts data: CY. 
So 16 - 3 => 13
"""

# Question 5
library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn)
length(grep("2012", sampleTimes)) #Only gets the first part, not which are Mondays

y12 <- sampleTimes[ grepl("2012", sampleTimes)]

length( grep("Monday", weekdays(y12)) )